### ISSUE TITLE
Gencode 19

### ISSUE THREAD

**Issue by zd1** [kauralasoo/txrevise#1]
Hi there, 

Thanks for making the txrevise package. I would like to generate transcription events for Gencode 19, since all the rest of my analyses are based on this version. 

This corresponds to Ensembl version 74, 75 (https://www.gencodegenes.org/releases/). 

I've read the vignette but I am not sure how I should prepare the input data.

http://htmlpreview.github.io/?https://github.com/kauralasoo/txrevise/blob/master/inst/doc/construct_events.html

Thanks,
Zhihao

**Comment by kauralasoo** [comment]
Hi Zhihao,

Thank your for your interest in txrevise. I agree that the instructions are not as clear as they could be. Hopefully by the end of this week I will have updated instruction on how to construct the events directly from GTF files. 

Best,
Kaur

**Comment by zd1** [comment]
Thanks very much for your prompt reply. I look forward to reading the updated document. 

Best, 
Zhihao

**Comment by zd1** [comment]
Hi Kaur, 

I have a question on the version of the precomputed set

GRCh37(hg19) + Ensembl 90

According to this page from Gencode, Ensembl 90 corresponds to Gencode 27, which is mapped to GRCh38:
https://www.gencodegenes.org/releases/

The latest Gencode that is mapped to GRCh37 is Gencode 19. I am not fully familiar with their versions. But could you give a bit more elaboration on this?

Thank you, 
Zhihao

**Comment by kauralasoo** [comment]
Hi Zhihao,
I have now modified the README.md file with step-by-step instruction for creating event annotations from the Ensembl GTF file. I have tested it with Ensembl version 92, but I haven't tried the earlier versions yet. I consider this now to be the preferred way for constructing event annotations, because it only requires the GTF file as input and does not depend on the Ensembl biomart (which seems to be bit unstable). 

Let me know if anything is unclear or does not work for you and I'll try to fix it. Also, I would recommend to use the Ensembl GTF file instead of the GENCODE GTF file, because the Ensembl release contains many more transcripts and will thus produce more events. Empirically, I have noticed that some of the differentially regulated events are not part of the GENCODE Basic set of transcripts.

The GRCh37(hg19) + Ensembl 90 events were constructed using data from the GRCh37 version of the Ensembl biomart (available at http://grch37.ensembl.org/index.html), but since the biomaRt R package tends to be a bit unstable, I would not recommend to use this approach anymore. However, it might be worth trying the GTF dumps available from here: http://grch37.ensembl.org/info/data/ftp/index.html ( they currently have GRCh37 + Ensembl 87).

Best,
Kaur

**Comment by zd1** [comment]
Hi Kaur, 

Thanks very much for your reply. It's very helpful. I'll try to follow the updated instructions. 

Best,
Zhihao

**Comment by zd1** [comment]
Hi Kaur, 

I am trying to run through the steps for making annotations based on Gencode 19 (ensembl 75). 

I've got to this line: 
https://github.com/kauralasoo/txrevise/blob/86d9431589aedce50c220ad7d45cbf23a574a384/scripts/prepareAnnotations.R#L25

and encountered an error:

`Error in mutate_impl(.data, dots) : 
  Binding not found: transcript_biotype.`

which points to this line:

https://github.com/kauralasoo/txrevise/blob/a95eb8e63183bd7d3eeeb7052725f6dcc7b3254e/R/processEnsemblAnnotations.R#L33

I don't see transcript_biotype set before this position. Any idea what's gone wrong?

Thanks,
Zhihao

**Comment by kauralasoo** [comment]
Hi Zhihao,

The problem seems to be that the Ensembl 75 GTF file does not contain the 'transcript_biotype' field required by txrevise. I would just use the Homo_sapiens.GRCh37.87.gtf.gz file that has this field. It's the same version of the reference genome (GRCh37) and using a newer Ensembl build will probably just yield a some additional transcriptional events. Keep in mind that txrevise modifies the original transcript annotations significantly anyway.

Unfortunately I do not plan to support the old Ensembl GTF files.

Best,
Kaur

**Comment by zd1** [comment]
Thanks Kaur. I switched to GRCh37.87 and have got to the step of running constructEvents.R, looking promising. 

Best,
Zhihao

**Comment by zd1** [comment]
Hi Kaur, 

I have managed to generate the gff3 files following the instructions provided in the README. Thank you. Here are some example lines

`9       txrevise        gene    128305338       128469510       .       -       .       Parent=NA;ID=ENSG00000119487.grp_1.upstream;gene_id=ENSG00000119487.grp_1.upstream
9       txrevise        mRNA    128305338       128469510       .       -       .       Parent=ENSG00000119487.grp_1.upstream;ID=ENSG00000119487.grp_1.upstream.ENST00000373511;gene_id=ENSG00000119487.grp_1.upstream
9       txrevise        exon    128305338       128305447       .       -       .       Parent=ENSG00000119487.grp_1.upstream.ENST00000373511;ID=exon:ENSG00000119487.grp_1.upstream.ENST00000373511:1;gene_id=ENSG00000119487.grp_1.upstream
9       txrevise        exon    128347834       128348006       .       -       .       Parent=ENSG00000119487.grp_1.upstream.ENST00000373511;ID=exon:ENSG00000119487.grp_1.upstream.ENST00000373511:2;gene_id=ENSG00000119487.grp_1.upstream
9       txrevise        exon    128362114       128362206       .       -       .       Parent=ENSG00000119487.grp_1.upstream.ENST00000373511;ID=exon:ENSG00000119487.grp_1.upstream.ENST00000373511:3;gene_id=ENSG00000119487.grp_1.upstream
9       txrevise        exon    128419930       128420078       .       -       .       Parent=ENSG00000119487.grp_1.upstream.ENST00000373511;ID=exon:ENSG00000119487.grp_1.upstream.ENST00000373511:4;gene_id=ENSG00000119487.grp_1.upstream
`
I then used software Salmon to do the quantification using this gff3 as the geneMap, and the gencode 19 fasta as reference (after indexed by Salmon) [here is the gencode fasta file gencode.v19.pc_transcripts.fa.gz](ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.pc_transcripts.fa.gz) . 

The problem is that for many of the ENSG IDs in the output, I don't find them in the geneMap file. For example, these are the first few lines in the `quant.sf` made by Salmon for one sample but I don't see them in the geneMap: GRCh37.87/txrevise.grp_1.upstream.gff3 

`Name    Length  EffectiveLength TPM     NumReads
ENST00000361789.2|ENSG00000198727.2|-|-|MT-CYB-201|MT-CYB|1141|CDS:1-1141|      1141    945.825 6008.84 115026
ENST00000361567.2|ENSG00000198786.2|-|-|MT-ND5-201|MT-ND5|1812|CDS:1-1812|      1812    1616.83 1789.27 58551
ENST00000361335.1|ENSG00000212907.2|-|-|MT-ND4L-201|MT-ND4L|297|CDS:1-297|      297     119.26  12780.6 30849
ENST00000361227.2|ENSG00000198840.2|-|-|MT-ND3-201|MT-ND3|346|CDS:1-346|        346     160.77  7259.38 23621
ENST00000361851.1|ENSG00000228253.1|-|-|MT-ATP8-201|MT-ATP8|207|CDS:1-207|      207     55.671  15627.7 17608.3
ENST00000361453.3|ENSG00000198763.3|-|-|MT-ND2-201|MT-ND2|1042|CDS:1-1042|      1042    846.825 7268.28 124572
ENST00000361390.2|ENSG00000198888.2|-|-|MT-ND1-201|MT-ND1|956|CDS:1-956|        956     760.934 7137    109915
ENST00000602680.1|ENSG00000185894.4|OTTHUMG00000045199.2|OTTHUMT00000467695.1|BPY2C-003|BPY2C|559       559     364.687 0       0
ENST00000382287.1|ENSG00000185894.4|OTTHUMG00000045199.2|OTTHUMT00000104944.1|BPY2C-001|BPY2C|1206      1206    1010.83 0       0
`
I am getting large amount of warnings like this:
`[2018-07-02 17:16:00.111] [jointLog] [warning] couldn't find transcript named [ENST00000361789.2|ENSG00000198727.2|-|-|MT-CYB-201|MT-CYB|1141|CDS:1-1141|] in transcript <-> gene map; returning transcr
ipt as it's own gene`

It seems to me that transcripts in the fasta file and the gff3 file are not matching up. Am I mistaken here about this process? Any advice would be appreciated. 

Thanks!
Zhihao

**Comment by kauralasoo** [comment]
Hi Zhihao,

Thank you for you questions, these really help me to improve the documentation for txrevise! 

Your problem seems to be that you are using the Gencode 19 fasta as the reference. Instead, you need to construct your own FASTA files for each set of transcription event (6 fasta files in total). You can do this easily with gffread tool from the cufflinks package, all you need is the fasta file of the GRCh37 reference genome. I have just added an example at the end of the README file. 

I have also also update the pre-computed event annotations based on the latest GTF files from Ensembl for both GRCh37 (v87) and GRCh38 (v92) (See README). 

Best,
Kaur

**Comment by zd1** [comment]
Thanks Kaur for the explanations. It makes sense to me now. I've made fasta files for each of the gff3 files using gffread as your suggested. I run Salmon on a few samples and they went fine. 

Also thanks for making the precomputed datasets. I checked a few of those against mine and they've got same number of lines, which is encouraging. Hopefully this is resolved now. 

Best,
Zhihao

**Comment by zd1** [comment]
Hi Kaur, 

I've been doing QTL mapping using the txRevised annotations. The differences between Gencode 19 and Gencode 25 (corresponding to GRCh37 Ensembl 87) has come up again. I took the precomputed set of txRevise annotations and compared that against gff3 downloaded from the gencode website. 

Here's a summary table. I was wondering if you have any insights on this, especially the 7127 transcripts that are only found in txrevise when compared against gencode25?

![screenshot from 2018-08-15 17-06-42](https://user-images.githubusercontent.com/814295/44158900-e9f90e80-a0ad-11e8-83e7-b088aa85d7ad.png)

Thanks, 
Zhihao
